language: go
go:
    - 1.14.x

before_install:
    - go get -t -v ./...

install:
    - go get github.com/Sperax/bdls/

script:
    - go test -coverprofile=coverage.txt -covermode=atomic -timeout 12h -bench .

after_success:
    - bash <(curl -s https://codecov.io/bash)
