language: go
go:
    - 1.14.x

before_install:
    - go get -t -v ./...

install:
    - go get github.com/Sperax/bdls/

script:
    - go test -v -coverprofile=coverage.txt.tmp -covermode=atomic -timeout 12h -run "(Verify)|(Full50)|(Partial50)"
    - cat coverage.txt.tmp | grep -v "pb.go" > coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
